name: class_information_system
description: class information system app

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.18.0+1
  adobe_xd: ^1.0.0+1
  hexcolor: ^1.0.4
  cupertino_icons: ^0.1.3
  flutter_spinkit: ^4.0.0
  firebase_core : ^0.5.0
  flutter_statusbarcolor: ^0.2.3
  dotted_line: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/


  
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/Product Sans Bold.ttf
        - asset: fonts/Product Sans Regular.ttf
  
